name: CraftLobby
main: cz.wake.lobby.Main
version: "2.0"
api-version: "1.14"
author: MrWakeCZ
softdepend: [RogueParkour,LuckPerms,NPCLibPlugin]
depend: [Multiverse-Core,CraftCore]

permissions:
  craftlobby.pristup:
    description: Beta test
